parameters:
#    dan_user.example.class: Dan\UserBundle\Example
    oauth.user_provider.class: Dan\UserBundle\Security\FOSUBUserProvider
 
services:
    oauth.user_provider:
        class: "%oauth.user_provider.class%"
        arguments: 
            - @fos_user.user_manager
            - {google: googleId, facebook: facebookId}

#    fos_google.user_provider:
#        class: Dan\UserBundle\Security\GoogleProvider
#        arguments:
#            google: @fos_google.api
#            userManager: @fos_user.user_manager
#            validator: @validator
#            em: @doctrine.orm.entity_manager
#            kernel: @kernel
            
    user.factory:
        class: Dan\UserBundle\Service\User
        arguments: [@security.context]
        
    user:
        class: Dan\UserBundle\Entity\User
        factory_service: user.factory
        factory_method: get


    dan_user.registration.form.type:
        class: Dan\UserBundle\Form\Type\RegistrationFormType
        arguments: [Dan\UserBundle\Entity\User]
        calls:
            - [ setUserManager, [ @fos_user.user_manager ]]
        tags:
            - { name: form.type, alias: dan_user_registration }

    dan_user.resetting.form.type:
        class: Dan\UserBundle\Form\Type\ResettingFormType
        tags:
            - { name: form.type, alias: dan_user_resetting }
            
    dan_user.change_password.form.type:
        class: Dan\UserBundle\Form\Type\ChangePasswordFormType
        tags:
            - { name: form.type, alias: dan_user_change_password }
            
    dan_user.profile.form.type:
        class: Dan\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: dan_user_profile_account }

    model.manager.user:
        class: Dan\UserBundle\Model\UserManager
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @fos_user.entity_manager
            - %fos_user.model.user.class%
        calls:
            - [setKernel,[@kernel]]
            
    dan_user.twig.image_extension:
        class: Dan\UserBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }
